version: "3"
services:
  app:
    build: ./sample
  runner:
    build: ./runner
    command: test tests.js --initial-url=http://app:3000
    volumes:
      - ./out:/app/screenshots
    depends_on: 
    - app